---
- name: Add VLAN 100 to Cisco Switch Interface
  hosts: all #make sure to use --limit to only hosts you want to target
  gather_facts: no
  tasks:
    - name: Ensure VLAN 100 exists
      cisco.ios.ios_vlan:
        vlan_id: 100
        name: "vlan100"
        state: present

    - name: Assign VLAN to Interface
      cisco.ios.ios_config:
        lines:
          - "switchport access vlan 100"
        parents: "interface GigabitEthernet1/0/25"
