---
- name: Create file with 640 permissions
  hosts: web1
  gather_facts: no
  tasks:
    - file:
        path: /opt/data/perm.txt
        state: touch
        mode: '0640'

---
- name: Insert Files with Text
  hosts: web1
  gather_facts: no
  tasks:
    - file:
        path: /var/www/html/index.html
        state: touch
        mode: '0766'

    - lineinfile:
        path: /var/www/html/index.html
        line: This line was added using Ansible lineinfile module!

---
- hosts: web1
  name: find 2m old files greater than or equal to 1m 
  tasks:
    - name: Find files
      find:
        paths: /opt/data
        recurse: yes
        age: 2m
        size: 1m
      register: file

    - name: Copy files
      command: "cp {{ item.path }} /opt"
      with_items: "{{ file.files }}"

---
- name: Insert Files with Text
  hosts: web1
  gather_facts: no
  tasks:
    - name: Insert block text after
      blockinfile:
         path: /var/www/html/index.html
         block: |
            Welcome to KodeKloud!
            
            This is Ansible Lab.

---
- name: Change listening port from 80 to 8080
  hosts: web1
  gather_facts: no
  tasks:
     - name: Supports a validate command
       replace:
           path: /etc/httpd/conf/httpd.conf
           regexp: 'Listen 80'
           replace: 'Listen 8080'

     - name: restart httpd
       service:
          name: httpd
          state: restarted